name: Android CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Write signing.jks
        shell: bash
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$SIGNING_KEY" | base64 -d > signing.jks

      - name: Write keystore.properties
        shell: bash
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
        run: |
          cat > keystore.properties<< EOF
          storePassword=$KEY_STORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$ALIAS
          storeFile=$GITHUB_WORKSPACE/signing.jks
          EOF

      - name: Assemble release version
        run: ./gradlew --no-daemon --build-cache -PbuildNumber=${{ github.run_number }} checkPreCI clean check assembleRelease

      - name: Archive reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            app/build/reports/lint-results-debug.html
            app/build/reports/tests/testDebugUnitTest/
            app/build/reports/tests/testReleaseUnitTest/

      - name: Upload apk to AppCenter
        uses: zackify/AppCenter-Github-Action@1.0.0
        with:
          appName: Orgmir/Ler
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: beta%20testers
          file: app/build/outputs/apk/release/app-release.apk
