name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble release version
        run: ./gradlew assembleRelease

      - name: Upload apk to AppCenter
        uses: zackify/AppCenter-Github-Action@1.0.0
          with:
            appName: Orgmir/Ler
            token: ${{secrets.APP_CENTER_TOKEN}}
            group: beta%20testers
            file: app/build/outputs/apk/release/app-release-unsigned.apk


    
